### ISSUE TITLE
LGACServer enters fail state

### ISSUE THREAD

**Issue by heggink** [olinek2/LGAC_SmartT#1]
Having been away for a while, I noticed yesterday that my Aircon no longer responded to commands from domoticz. Restarting the service fixed it again.
Looking in the daemon log, I saw a bunch of errors:
server: ac result {'cmd': 'status', 'exception': "python-LGAC: ('Connection aborted.', OSError(0, 'Error'))"}
then folowed by a bunch of:
ac result {'cmd': 'status', 'exception': "python-LGAC: 'Monitor' object has no attribute 'work_id'"}

Any idea whether some error handling can be built in (like a simple restart)?

**Comment by mflammia** [comment]
Quick thank you for creating the code, look forward to getting it working :)

Just at this step of the process:

"The script will ask you to open a browser, log in, and then paste the URL you're redirected to. It will then write a JSON file called wideq_state.json._"

I copy the URL into the browser, enter my LG account details and it just keeps coming back with the message:

us.m.lgaccount.com says:
Please check your network and try again

I can login with the same account to the following:

https://sso.lg.com/oauth/page/login?authorizeKey=9c837df5-72db-4991-82e6-451be0636657

There is an option to login with facebook, which then returns the following URL:

https://us.m.lgaccount.com/login/sign_in?country=UK&language=en-EN&svcCode=SVC202&authSvr=oauth2&client_id=LGAO221A02&onyx_feature=N&division=ha&show_select_country=N&show_add_services=N&oauthTokenExpiredFlag=N&os_type=PC&thirdParty=facebook#_=_

The reference to "oauthTokenExpiredFlag" might be because of the elements in the wideq.py have expired?

SVC_CODE = 'SVC202'
CLIENT_ID = 'LGAO221A02'
OAUTH_SECRET_KEY = 'c053c2a6ddeb7ad97cb0eed0dcb31cf8'
OAUTH_CLIENT_KEY = 'LGAO221A02'

In which case, do you know how to update these?

Many thanks in advance.
